### ISSUE TITLE
possible downgrade to 1.12?

### ISSUE THREAD

**Issue by Schp4wn** [amoschu/dark-souls-death-screen#1]
hey there, I have no Idea how I could contact you otherwise - is it possible for you to adapt this for Vanilla Wow 1.12

**Comment by amoschu** [comment]
From a glance over [this wiki](http://vanilla-wow.wikia.com/wiki/Widget_API), it seems like the `Animation` api was only added in 3.1.0. I'm not sure how I'd implement the main functionality without it, sorry.

**Comment by Schp4wn** [comment]
https://www.youtube.com/watch?v=8edId6mSIY0
this is what I got so far^^

**Comment by Schp4wn** [comment]
https://youtu.be/x3W32ZiMuYc

**Comment by amoschu** [comment]
Looks good! You don't even need me :)
